# permissions for end users to edit cronjob2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob2-editor-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjob2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjob2s/status
  verbs:
  - get
